### ISSUE TITLE
pre-commit: `PermissionError` while installing

### ISSUE THREAD

**Issue by eggplants** [cmhughes/latexindent.pl#369]
## yaml settings

- `.pre-commit-config.yaml`

```yaml
# pip install pre-commit
# pre-commit install
# pre-commit run --all-files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      # - id: destroyed-symlinks
      # - id: double-quote-string-fixer
      - id: end-of-file-fixer
        exclude: tests/test_changes/
        files: \.(py|sh|rst|yml|yaml)$
      # - id: name-tests-test
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
      # - id: requirements-txt-fixer
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: [--py37-plus]
      - id: nbqa-isort
  - repo: https://github.com/cmhughes/latexindent.pl.git
    rev: V3.17.3
    hooks:
      - id: latexindent
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14
    hooks:
      - id: mdformat
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        args: [--disable=MD013]
```

## actual/given output

```shellsession
$ uname -vorm
5.15.0-33-generic #34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 GNU/Linux

$ pre-commit -V
pre-commit 2.19.0

$ pre-commit install
pre-commit installed at .git/hooks/pre-commit

$ pre-commit
[INFO] Initializing environment for https://github.com/cmhughes/latexindent.pl.git.
[INFO] Initializing environment for https://github.com/executablebooks/mdformat.
[INFO] Installing environment for https://github.com/cmhughes/latexindent.pl.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[sudo] password for eggplants:
An unexpected error has occurred: PermissionError: [Errno 13] Permission denied: '/home/eggplants/.cache/pre-commit/repo95rn1aiq/perl_env-default/.install_state_v1staging'
Check the log at /home/eggplants/.cache/pre-commit/pre-commit.log

$
```

**Comment by eggplants** [comment]
- `/home/eggplants/.cache/pre-commit/pre-commit.log`
### version information

```
pre-commit version: 2.19.0
git --version: git version 2.34.1
sys.version:
    3.10.4 (main, May 22 2022, 05:10:45) [GCC 11.2.0]
sys.executable: /home/eggplants/.pyenv/versions/3.10.4/bin/python3.10
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: PermissionError: [Errno 1] Operation not permitted: '/home/eggplants/.cache/pre-commit/repo95rn1aiq/perl_env-default/lib/perl5/LatexIndent/BlankLines.pm'
```

```
Traceback (most recent call last):
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/shutil.py", line 676, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'BlankLines.pm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/main.py", line 389, in main
    return run(args.config, store, args)
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/repository.py", line 77, in _hook_install
    rmtree(hook.prefix.path(venv))
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/util.py", line 257, in rmtree
    shutil.rmtree(path, ignore_errors=False, onerror=handle_remove_readonly)
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/shutil.py", line 722, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/shutil.py", line 655, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/shutil.py", line 678, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/pre_commit/util.py", line 253, in handle_remove_readonly
    os.chmod(p, os.stat(p).st_mode | stat.S_IWUSR)
PermissionError: [Errno 1] Operation not permitted: '/home/eggplants/.cache/pre-commit/repo95rn1aiq/perl_env-default/lib/perl5/LatexIndent/BlankLines.pm'
```

**Comment by cmhughes** [comment]
@Holzhaus @tdegeus any ideas?

**Comment by eggplants** [comment]
If I had a Dockerfile, I feel like I could run it with [`docker_image` like pre-commit-shfmt](https://github.com/pecigonzalo/pre-commit-shfmt/blob/d9fbdb88841c1fe241aadff129167c323e394067/.pre-commit-hooks.yaml#L18-L33) and it would not fail with local permissions.

**Comment by cmhughes** [comment]
https://github.com/csg-projects/latexindent-dockerfile

**Comment by eggplants** [comment]
### Suggestion

```yml
- id: latexindent-docker
  name: latexindent.pl
  description: Run latexindent.pl (get dependencies using DockerHub)
  entry: csegarragonz/latexindent
  language: docker_image
  types:
    - tex
```

**Comment by tdegeus** [comment]
I don't know what is going on, but I do think it might be more the pre-commit core that should be queried: the Perl package that poses problems might not even be a direct dependency of latenindent.

Regardless you could work around with the latexindent-conda hook, that use Conda's Perl

**Comment by cmhughes** [comment]
Thanks for your work on docker @eggplants  :)

I've released V3.18 https://github.com/cmhughes/latexindent.pl/releases/tag/V3.18

Are you happy if we close this issue?

**Comment by cmhughes** [comment]
@eggplants can you take a look at the error log at

https://github.com/cmhughes/latexindent.pl/actions/runs/3816377283/workflow

Any ideas what has gone wrong?

**Comment by cmhughes** [comment]
@eggplants please ignore my previous message, all resolved :)
